config/routes.rb
Rails.application.routes.draw do

  get 'users/new'

  get 'users/create'

  get 'sessions/new'

  get 'sessions/create'

  get 'sessions/destroy'

  get 'users/new'

  get 'users/create'

  get 'reservations/show'

  get 'restaurants' => 'restaurants#index'
  get 'restaurants/:id' => 'restaurants#show', as: 'restaurant'


  resources :restaurants do
  resources :reservations, only: [:new, :create, :show, :destroy]
  end 

end

Seaty::Application.routes.draw do
  resources :restaurants
  resources :sessions, :reservations, :users, only: [:new, :create, :delete, :destroy]
end

app/models/category.rb
class Category < ActiveRecord::Base
end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
	belongs_to :user
	belongs_to :restaurant
end

app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reservations
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
	has_many :reservations
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
 :ensure_logged_in
  protect_from_forgery with: :exception

  
   def ensure_logged_in
    unless current_user
      flash[:alert] = "Please log in."
    end
  end
  
private

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  helper_method :current_user

end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController

  before_filter :load_restaurant
  before_filter :ensure_logged_in, only: [:create, :destroy]

  def show
    @reservation = Reservation.find(params[:id])
    end

   def new
    @reservation = @restaurant.reservations.build
  end

  def create
    @reservation = @restaurant.reservations.build(reservation_params)
    @reservation.user = current_user

    if @reservation.save
      redirect_to restaurants_path, notice: 'Your reservation has been successfully booked!'
    else
      render 'restaurants/show'
    end
  end

  def destroy
    @reservation = Reservation.find(params[:id])
    @reservation.destroy
  end

  private
  def reservation_params
    params.require(:reservation).permit(:people, :time, :date, :comment, :id).merge({user_id: current_user.id})
  end

  def load_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController

	def index
	@restaurants = Restaurant.all
	end

	def new
		@restaurant = Restaurant.new
	end

	def show
	  @restaurant = Restaurant.find(params[:id])
	  if current_user
	    @reservation = @restaurant.reservations.build
	  end
  	end

	
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  :ensure_logged_in
  
 def new
  end

  def create
    user = User.find_by(email: params[:email])
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to restaurants_url, :notice => "Logged in!"
    else
      flash.now[:alert] = "Invalid email or password"
      render "new"
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to restaurants_url, notice: "Logged out!"
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to restaurants_url, notice: "Signed up!"
    else
      render "new"
    end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy
    redirect_to restaurants_path
  end

  private
  def user_params
    params.require(:user).permit(:email, :password, :delete, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/reservations_helper.rb
module ReservationsHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Seaty</title>
  

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>

<body>
  <% if flash[:notice] %>
    <p id="notice"><%= flash[:notice] %></p>
  <% end %>
  <% if flash[:alert] %>
    <p id="alert"><%= flash[:alert] %></p>
  <% end %>

  

  <%= yield %>
    


  <p class="userinfo">
    <% if current_user %>
      Signed in as <%= current_user.email %>. <%= link_to "Log out", session_path("current"), :method => :delete %>
    <% else %>
      <%= link_to "Log in", new_session_path %> or <%= link_to "Sign up", new_user_path %>
    <% end %>
  </p>



</body>
</html>

app/views/reservations/new.html.erb
<% if current_user %>
  <h4>New Reservation</h4>

  <%= form_for([@restaurant, @reservation]) do |f| %>
    <% if @reservation.errors.any? %>
      <div id="error_explanation">
        <h2><%= pluralize(@reservation.errors.count, "error") %> Unable to book servation </h2>

        <ul>
        <% @reservation.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    <% end %>

    <div class="field">
      <%= f.label :time %><br />
      <%= f.text_area :time %> <br>
      <%= f.label :Number_of_Guests %><br />
      <%= f.text_area :people%>
    </div>
    <div class="actions">
      <%= f.submit %>
    </div>
  <% end %>

<% else %>
  <p>Please <%= link_to "log in", new_session_path %> to book a reservation.</p> 
<% end %>
.

app/views/reservations/show.html.erb
<%= @reservations each do |f| %>

app/views/restaurants/index.html.erb
<nav class="fixed-nav-bar">
	<h2> S E A T Y O U R S E L F</h2>
</nav>
<head></head>

<div class="wide"> .. </div>
<div class="navbar"> </div>

<div class="container"> 


<h1>Restaurants</h1>

<% @restaurants.each do |restaurant| %>

 <b> <%= link_to(restaurant.name, restaurant_path(restaurant) ) %> </b> <br>
  <%= restaurant.address %>, <%= restaurant.neighbourhood %> <br>
  <%= restaurant.category %> <br> 
  <%= restaurant.pricerange %><p> 

  <%= restaurant.description %><br>
  <%= restaurant.timeslots %></p>

<% end %>


</body>
</div>

app/views/restaurants/show.html.erb
<H1> <%= @restaurant.name %> </H1> <br> 
  <%= @restaurant.address %>, <%= @restaurant.neighbourhood %> <br>
  <%= @restaurant.category %> <br> 
  <%= @restaurant.pricerange %><p> 

  <%= @restaurant.description %><br>
  <%= @restaurant.timeslots %></p>

<% if current_user %>

<%= link_to "Book your reservation", new_restaurant_reservation_path(@restaurant) %>

  <% else %>
  <p>Please <%= link_to "log in", new_session_path %></p> 
<% end %>

app/views/users/create.html.erb
<h1>Users#create</h1>
<p>Find me in app/views/users/create.html.erb</p>

app/views/users/new.html.erb
<h1>Sign Up</h1>

<%= form_for @user do |f| %>
  <% if @user.errors.any? %>
    <div class="error_messages">
      <h2>Form is invalid</h2>
      <ul>
        <% for message in @user.errors.full_messages %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :email %><br/>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :password %><br/>
    <%= f.password_field :password %>
  </div>
  <div class="field">
    <%= f.label :password_confirmation %><br/>
    <%= f.password_field :password_confirmation %>
  </div>
  <div class="actions"><%= f.submit %></div>
<% end %>